-   id: norminette-hook
    name: Norminette hook
    description: Runs norminette within pre-commit.
    entry: norminette-hook
    language: python
    types: [file]
    files: \.(h|c)$
    minimum_pre_commit_version: 2.9.0
